//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConasiCRM.Portable.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConasiCRM.Portable.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xóa người ủy quyền không ?.
        /// </summary>
        internal static string ban_co_muon_xoa_nguoi_uy_quyen_nay_khong {
            get {
                return ResourceManager.GetString("ban_co_muon_xoa_nguoi_uy_quyen_nay_khong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đang sử dụng mật khẩu cũ. Vui lòng nhập lại.
        /// </summary>
        internal static string ban_dang_su_dung_mat_khau_cu_vui_long_nhap_lai {
            get {
                return ResourceManager.GetString("ban_dang_su_dung_mat_khau_cu_vui_long_nhap_lai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng tính giá.
        /// </summary>
        internal static string bang_tinh_gia_appshell {
            get {
                return ResourceManager.GetString("bang_tinh_gia_appshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cá nhân.
        /// </summary>
        internal static string ca_nhan {
            get {
                return ResourceManager.GetString("ca_nhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập Nhật.
        /// </summary>
        internal static string cap_nhat {
            get {
                return ResourceManager.GetString("cap_nhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật khách hàng.
        /// </summary>
        internal static string cap_nhat_khach_hang {
            get {
                return ResourceManager.GetString("cap_nhat_khach_hang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập Nhật KH Cá Nhân.
        /// </summary>
        internal static string cap_nhat_khach_hang_ca_nhan_title {
            get {
                return ResourceManager.GetString("cap_nhat_khach_hang_ca_nhan_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập Nhật KH Doanh Nghiệp.
        /// </summary>
        internal static string cap_nhat_khach_hang_doanh_nghiep_title {
            get {
                return ResourceManager.GetString("cap_nhat_khach_hang_doanh_nghiep_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập Nhật KH Tiềm Năng.
        /// </summary>
        internal static string cap_nhat_khach_hang_tiem_nang_title {
            get {
                return ResourceManager.GetString("cap_nhat_khach_hang_tiem_nang_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        internal static string cap_nhat_thanh_cong {
            get {
                return ResourceManager.GetString("cap_nhat_thanh_cong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thất bại.
        /// </summary>
        internal static string cap_nhat_that_bai {
            get {
                return ResourceManager.GetString("cap_nhat_that_bai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chăm Sóc Khách Hàng.
        /// </summary>
        internal static string cham_soc_khach_hang {
            get {
                return ResourceManager.GetString("cham_soc_khach_hang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiến dịch.
        /// </summary>
        internal static string chien_dich {
            get {
                return ResourceManager.GetString("chien_dich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        internal static string chinh_sua {
            get {
                return ResourceManager.GetString("chinh_sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ảnh từ thư viện.
        /// </summary>
        internal static string chon_anh_tu_thu_vien {
            get {
                return ResourceManager.GetString("chon_anh_tu_thu_vien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn chiến dịch.
        /// </summary>
        internal static string chon_chien_dich {
            get {
                return ResourceManager.GetString("chon_chien_dich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn công ty.
        /// </summary>
        internal static string chon_cong_ty {
            get {
                return ResourceManager.GetString("chon_cong_ty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn đánh giá.
        /// </summary>
        internal static string chon_danh_gia {
            get {
                return ResourceManager.GetString("chon_danh_gia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn địa chỉ công ty.
        /// </summary>
        internal static string chon_dia_chi_cong_ty {
            get {
                return ResourceManager.GetString("chon_dia_chi_cong_ty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn địa chỉ liên lạc.
        /// </summary>
        internal static string chon_dia_chi_lien_lac {
            get {
                return ResourceManager.GetString("chon_dia_chi_lien_lac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn địa chỉ thường trú.
        /// </summary>
        internal static string chon_dia_chi_thuong_tru {
            get {
                return ResourceManager.GetString("chon_dia_chi_thuong_tru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn địa chỉ trụ sở chính.
        /// </summary>
        internal static string chon_dia_chi_tru_so_chinh {
            get {
                return ResourceManager.GetString("chon_dia_chi_tru_so_chinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn giới tính.
        /// </summary>
        internal static string chon_gioi_tinh {
            get {
                return ResourceManager.GetString("chon_gioi_tinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn lĩnh vực.
        /// </summary>
        internal static string chon_linh_vuc {
            get {
                return ResourceManager.GetString("chon_linh_vuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn loại khách hàng.
        /// </summary>
        internal static string chon_loai_khach_hang {
            get {
                return ResourceManager.GetString("chon_loai_khach_hang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ngày cấp.
        /// </summary>
        internal static string chon_ngay_cap {
            get {
                return ResourceManager.GetString("chon_ngay_cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ngày sinh.
        /// </summary>
        internal static string chon_ngay_sinh {
            get {
                return ResourceManager.GetString("chon_ngay_sinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn người đại diện.
        /// </summary>
        internal static string chon_nguoi_dai_dien {
            get {
                return ResourceManager.GetString("chon_nguoi_dai_dien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn nguồn khách hàng.
        /// </summary>
        internal static string chon_nguon_khach_hang {
            get {
                return ResourceManager.GetString("chon_nguon_khach_hang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn quốc tịch.
        /// </summary>
        internal static string chon_quoc_tich {
            get {
                return ResourceManager.GetString("chon_quoc_tich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có contact, không thể chỉnh sửa thông tin.
        /// </summary>
        internal static string chua_co_contact_khong_the_chinh_sua_thong_tin {
            get {
                return ResourceManager.GetString("chua_co_contact_khong_the_chinh_sua_thong_tin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        internal static string chuc_vu {
            get {
                return ResourceManager.GetString("chuc_vu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ (EN).
        /// </summary>
        internal static string chuc_vu_en {
            get {
                return ResourceManager.GetString("chuc_vu_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ (VN).
        /// </summary>
        internal static string chuc_vu_vn {
            get {
                return ResourceManager.GetString("chuc_vu_vn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chụp hình.
        /// </summary>
        internal static string chup_hinh {
            get {
                return ResourceManager.GetString("chup_hinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển đổi khách hàng.
        /// </summary>
        internal static string chuyen_doi_khach_hang {
            get {
                return ResourceManager.GetString("chuyen_doi_khach_hang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        internal static string cong_ty {
            get {
                return ResourceManager.GetString("cong_ty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công việc đã được hủy.
        /// </summary>
        internal static string cong_viec_da_duoc_huy {
            get {
                return ResourceManager.GetString("cong_viec_da_duoc_huy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công việc đã hoàn thành.
        /// </summary>
        internal static string cong_viec_da_hoan_thanh {
            get {
                return ResourceManager.GetString("cong_viec_da_hoan_thanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÔNG VIỆC HÔM NAY.
        /// </summary>
        internal static string cong_viec_hom_nay {
            get {
                return ResourceManager.GetString("cong_viec_hom_nay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công Việc.
        /// </summary>
        internal static string cong_viec_title {
            get {
                return ResourceManager.GetString("cong_viec_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuộc gọi đã được hủy.
        /// </summary>
        internal static string cuoc_goi_da_duoc_huy {
            get {
                return ResourceManager.GetString("cuoc_goi_da_duoc_huy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuộc gọi đã hoàn thành.
        /// </summary>
        internal static string cuoc_goi_da_hoan_thanh {
            get {
                return ResourceManager.GetString("cuoc_goi_da_hoan_thanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuộc Gọi.
        /// </summary>
        internal static string cuoc_goi_title {
            get {
                return ResourceManager.GetString("cuoc_goi_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuộc họp đã được hủy.
        /// </summary>
        internal static string cuoc_hop_da_duoc_huy {
            get {
                return ResourceManager.GetString("cuoc_hop_da_duoc_huy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuộc họp đã hoàn thành.
        /// </summary>
        internal static string cuoc_hop_da_hoan_thanh {
            get {
                return ResourceManager.GetString("cuoc_hop_da_hoan_thanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuộc Họp.
        /// </summary>
        internal static string cuoc_hop_title {
            get {
                return ResourceManager.GetString("cuoc_hop_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã bán.
        /// </summary>
        internal static string da_ban {
            get {
                return ResourceManager.GetString("da_ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã chuyển đổi.
        /// </summary>
        internal static string da_chuyen_doi {
            get {
                return ResourceManager.GetString("da_chuyen_doi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hủy.
        /// </summary>
        internal static string da_huy {
            get {
                return ResourceManager.GetString("da_huy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã nhận.
        /// </summary>
        internal static string da_nhan {
            get {
                return ResourceManager.GetString("da_nhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi. Vui lòng thử lại.
        /// </summary>
        internal static string da_xay_ra_loi_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("da_xay_ra_loi_vui_long_thu_lai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa người ủy quyền được chọn.
        /// </summary>
        internal static string da_xoa_nguoi_uy_quyen_duoc_chon {
            get {
                return ResourceManager.GetString("da_xoa_nguoi_uy_quyen_duoc_chon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại diện:.
        /// </summary>
        internal static string dai_dien_ {
            get {
                return ResourceManager.GetString("dai_dien_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại Diện Pháp Luật.
        /// </summary>
        internal static string dai_dien_phap_luat {
            get {
                return ResourceManager.GetString("dai_dien_phap_luat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string dang_nhap {
            get {
                return ResourceManager.GetString("dang_nhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        internal static string dang_xuat_appshell {
            get {
                return ResourceManager.GetString("dang_xuat_appshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá.
        /// </summary>
        internal static string danh_gia {
            get {
                return ResourceManager.GetString("danh_gia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách theo dõi.
        /// </summary>
        internal static string danh_sach_theo_doi_appshell {
            get {
                return ResourceManager.GetString("danh_sach_theo_doi_appshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt Cọc.
        /// </summary>
        internal static string dat_coc {
            get {
                return ResourceManager.GetString("dat_coc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt cọc.
        /// </summary>
        internal static string dat_coc_appshell {
            get {
                return ResourceManager.GetString("dat_coc_appshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string dia_chi {
            get {
                return ResourceManager.GetString("dia_chi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ:.
        /// </summary>
        internal static string dia_chi_ {
            get {
                return ResourceManager.GetString("dia_chi_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ liên lạc.
        /// </summary>
        internal static string dia_chi_lien_lac {
            get {
                return ResourceManager.GetString("dia_chi_lien_lac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ liên lạc : .
        /// </summary>
        internal static string dia_chi_lien_lac_ {
            get {
                return ResourceManager.GetString("dia_chi_lien_lac_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ thường trú.
        /// </summary>
        internal static string dia_chi_thuong_tru {
            get {
                return ResourceManager.GetString("dia_chi_thuong_tru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ thường trú : .
        /// </summary>
        internal static string dia_chi_thuong_tru_ {
            get {
                return ResourceManager.GetString("dia_chi_thuong_tru_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ trụ sở chính.
        /// </summary>
        internal static string dia_chi_tru_so_chinh {
            get {
                return ResourceManager.GetString("dia_chi_tru_so_chinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ trụ sở chính:.
        /// </summary>
        internal static string dia_chi_tru_so_chinh_ {
            get {
                return ResourceManager.GetString("dia_chi_tru_so_chinh_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa điểm.
        /// </summary>
        internal static string dia_diem {
            get {
                return ResourceManager.GetString("dia_diem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doanh nghiệp.
        /// </summary>
        internal static string doanh_nghiep {
            get {
                return ResourceManager.GetString("doanh_nghiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doanh thu mỗi năm.
        /// </summary>
        internal static string doanh_thu_moi_nam {
            get {
                return ResourceManager.GetString("doanh_thu_moi_nam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công.
        /// </summary>
        internal static string doi_mat_khau_thanh_cong {
            get {
                return ResourceManager.GetString("doi_mat_khau_thanh_cong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thất bại.
        /// </summary>
        internal static string doi_mat_khau_that_bai {
            get {
                return ResourceManager.GetString("doi_mat_khau_that_bai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tiền tệ.
        /// </summary>
        internal static string don_vi_tien_te {
            get {
                return ResourceManager.GetString("don_vi_tien_te", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        internal static string dong {
            get {
                return ResourceManager.GetString("dong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng bộ danh bạ.
        /// </summary>
        internal static string dong_bo_danh_ba_appshell {
            get {
                return ResourceManager.GetString("dong_bo_danh_ba_appshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý.
        /// </summary>
        internal static string dong_y {
            get {
                return ResourceManager.GetString("dong_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án:.
        /// </summary>
        internal static string du_an_ {
            get {
                return ResourceManager.GetString("du_an_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string email_ {
            get {
                return ResourceManager.GetString("email_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 2.
        /// </summary>
        internal static string email_2 {
            get {
                return ResourceManager.GetString("email_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 2 sai địng dạng.
        /// </summary>
        internal static string email_2_sai_dinh_dang {
            get {
                return ResourceManager.GetString("email_2_sai_dinh_dang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã được sử dụng.
        /// </summary>
        internal static string email_da_duoc_su_dung {
            get {
                return ResourceManager.GetString("email_da_duoc_su_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sai định dạng.
        /// </summary>
        internal static string email_sai_dinh_dang {
            get {
                return ResourceManager.GetString("email_sai_dinh_dang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhớ đăng nhập.
        /// </summary>
        internal static string ghi_nho_dang_nhap {
            get {
                return ResourceManager.GetString("ghi_nho_dang_nhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao Dịch.
        /// </summary>
        internal static string giao_dich {
            get {
                return ResourceManager.GetString("giao_dich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIAO DỊCH -.
        /// </summary>
        internal static string giao_dich_home {
            get {
                return ResourceManager.GetString("giao_dich_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giấy phép kinh doanh:.
        /// </summary>
        internal static string giay_phep_kinh_doanh {
            get {
                return ResourceManager.GetString("giay_phep_kinh_doanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng.
        /// </summary>
        internal static string gio_hang_appshell {
            get {
                return ResourceManager.GetString("gio_hang_appshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        internal static string gioi_tinh {
            get {
                return ResourceManager.GetString("gioi_tinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giữ Chỗ.
        /// </summary>
        internal static string giu_cho {
            get {
                return ResourceManager.GetString("giu_cho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giữ chỗ.
        /// </summary>
        internal static string giu_cho_appshell {
            get {
                return ResourceManager.GetString("giu_cho_appshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gọi đến.
        /// </summary>
        internal static string goi_den {
            get {
                return ResourceManager.GetString("goi_den", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gọi điện.
        /// </summary>
        internal static string goi_dien {
            get {
                return ResourceManager.GetString("goi_dien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gọi từ.
        /// </summary>
        internal static string goi_tu {
            get {
                return ResourceManager.GetString("goi_tu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi tài liệu tiếp thị.
        /// </summary>
        internal static string gui_tai_lieu_tiep_thi {
            get {
                return ResourceManager.GetString("gui_tai_lieu_tiep_thi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình chụp CMND.
        /// </summary>
        internal static string hinh_chup_cmnd {
            get {
                return ResourceManager.GetString("hinh_chup_cmnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        internal static string ho_ten {
            get {
                return ResourceManager.GetString("ho_ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOA HỒNG -.
        /// </summary>
        internal static string hoa_hong {
            get {
                return ResourceManager.GetString("hoa_hong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn Thành.
        /// </summary>
        internal static string hoan_thanh {
            get {
                return ResourceManager.GetString("hoan_thanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoạt động.
        /// </summary>
        internal static string hoat_dong_appshell {
            get {
                return ResourceManager.GetString("hoat_dong_appshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoạt Động.
        /// </summary>
        internal static string hoat_dong_title {
            get {
                return ResourceManager.GetString("hoat_dong_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hôm nay không có công việc.
        /// </summary>
        internal static string hom_nay_khong_co_cong_viec {
            get {
                return ResourceManager.GetString("hom_nay_khong_co_cong_viec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp Đồng.
        /// </summary>
        internal static string hop_dong {
            get {
                return ResourceManager.GetString("hop_dong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng.
        /// </summary>
        internal static string hop_dong_appshell {
            get {
                return ResourceManager.GetString("hop_dong_appshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng Tốt.
        /// </summary>
        internal static string huong_tot {
            get {
                return ResourceManager.GetString("huong_tot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng Xấu.
        /// </summary>
        internal static string huong_xau {
            get {
                return ResourceManager.GetString("huong_xau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string huy {
            get {
                return ResourceManager.GetString("huy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        internal static string khach_hang {
            get {
                return ResourceManager.GetString("khach_hang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng:.
        /// </summary>
        internal static string khach_hang_ {
            get {
                return ResourceManager.GetString("khach_hang_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng không có số điện thoại. Vui lòng kiểm tra lại.
        /// </summary>
        internal static string khach_hang_khong_co_sdt_vui_long_kiem_tra_lai {
            get {
                return ResourceManager.GetString("khach_hang_khong_co_sdt_vui_long_kiem_tra_lai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng mới.
        /// </summary>
        internal static string khach_hang_moi {
            get {
                return ResourceManager.GetString("khach_hang_moi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng phải từ 18 tuổi.
        /// </summary>
        internal static string khach_hang_phai_tu_18_tuoi {
            get {
                return ResourceManager.GetString("khach_hang_phai_tu_18_tuoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KHÁCH HÀNG TIỀM NĂNG.
        /// </summary>
        internal static string khach_hang_tiem_nang {
            get {
                return ResourceManager.GetString("khach_hang_tiem_nang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không cập nhật được khách hàng. Vui lòng thử lại.
        /// </summary>
        internal static string khong_cap_nhat_duoc_khach_hang_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("khong_cap_nhat_duoc_khach_hang_vui_long_thu_lai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không cập nhật được thông tin Imei.
        /// </summary>
        internal static string khong_cap_nhat_duoc_thong_tin_imei {
            get {
                return ResourceManager.GetString("khong_cap_nhat_duoc_thong_tin_imei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không chuyển đổi.
        /// </summary>
        internal static string khong_chuyen_doi {
            get {
                return ResourceManager.GetString("khong_chuyen_doi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu.
        /// </summary>
        internal static string khong_co_du_lieu {
            get {
                return ResourceManager.GetString("khong_co_du_lieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không liên hệ được.
        /// </summary>
        internal static string khong_lien_he_duoc {
            get {
                return ResourceManager.GetString("khong_lien_he_duoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không load được chiến dịch.
        /// </summary>
        internal static string khong_load_duoc_chien_dich {
            get {
                return ResourceManager.GetString("khong_load_duoc_chien_dich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không load được quận/huyện.
        /// </summary>
        internal static string khong_load_duoc_quan_huyen {
            get {
                return ResourceManager.GetString("khong_load_duoc_quan_huyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không load được quốc gia.
        /// </summary>
        internal static string khong_load_duoc_quoc_gia {
            get {
                return ResourceManager.GetString("khong_load_duoc_quoc_gia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không load được tỉnh thành.
        /// </summary>
        internal static string khong_load_duoc_tinh_thanh {
            get {
                return ResourceManager.GetString("khong_load_duoc_tinh_thanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không quan tâm.
        /// </summary>
        internal static string khong_quan_tam {
            get {
                return ResourceManager.GetString("khong_quan_tam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể qualify.
        /// </summary>
        internal static string khong_the_qualify {
            get {
                return ResourceManager.GetString("khong_the_qualify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thêm được khách hàng. Vui lòng thử lại.
        /// </summary>
        internal static string khong_them_duoc_khach_hang_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("khong_them_duoc_khach_hang_vui_long_thu_lai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin.
        /// </summary>
        internal static string khong_tim_thay_thong_tin {
            get {
                return ResourceManager.GetString("khong_tim_thay_thong_tin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin công ty.
        /// </summary>
        internal static string khong_tim_thay_thong_tin_cong_ty {
            get {
                return ResourceManager.GetString("khong_tim_thay_thong_tin_cong_ty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin khách hàng.
        /// </summary>
        internal static string khong_tim_thay_thong_tin_khach_hang {
            get {
                return ResourceManager.GetString("khong_tim_thay_thong_tin_khach_hang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin. Vui lòng thử lại.
        /// </summary>
        internal static string khong_tim_thay_thong_tin_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("khong_tim_thay_thong_tin_vui_long_thu_lai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy user.
        /// </summary>
        internal static string khong_tim_thay_user {
            get {
                return ResourceManager.GetString("khong_tim_thay_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích hoạt lại KH.
        /// </summary>
        internal static string kich_hoat_lai_kh {
            get {
                return ResourceManager.GetString("kich_hoat_lai_kh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Bàn Phong Thủy.
        /// </summary>
        internal static string la_ban_phong_thuy {
            get {
                return ResourceManager.GetString("la_ban_phong_thuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch làm việc.
        /// </summary>
        internal static string lich_lam_viec_appshell {
            get {
                return ResourceManager.GetString("lich_lam_viec_appshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lĩnh vực.
        /// </summary>
        internal static string linh_vuc {
            get {
                return ResourceManager.GetString("linh_vuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại:.
        /// </summary>
        internal static string loai_ {
            get {
                return ResourceManager.GetString("loai_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại khách hàng.
        /// </summary>
        internal static string loai_khach_hang {
            get {
                return ResourceManager.GetString("loai_khach_hang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kết nối đến Server.
        /// </summary>
        internal static string loi_ket_noi_den_server {
            get {
                return ResourceManager.GetString("loi_ket_noi_den_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi hoàn thành công việc. Vui lòng thử lại.
        /// </summary>
        internal static string loi_khi_hoan_thanh_cong_viec_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("loi_khi_hoan_thanh_cong_viec_vui_long_thu_lai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi hoàn thành cuộc gọi. Vui lòng thử lại.
        /// </summary>
        internal static string loi_khi_hoan_thanh_cuoc_goi_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("loi_khi_hoan_thanh_cuoc_goi_vui_long_thu_lai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi hoàn thành cuộc họp. Vui lòng thử lại.
        /// </summary>
        internal static string loi_khi_hoan_thanh_cuoc_hop_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("loi_khi_hoan_thanh_cuoc_hop_vui_long_thu_lai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi hủy công việc. Vui lòng thử lại.
        /// </summary>
        internal static string loi_khi_huy_cong_viec_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("loi_khi_huy_cong_viec_vui_long_thu_lai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi hủy cuộc gọi. Vui lòng thử lại.
        /// </summary>
        internal static string loi_khi_huy_cuoc_goi_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("loi_khi_huy_cuoc_goi_vui_long_thu_lai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi hủy cuộc họp. Vui lòng thử lại.
        /// </summary>
        internal static string loi_khi_huy_cuoc_hop_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("loi_khi_huy_cuoc_hop_vui_long_thu_lai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã SIC.
        /// </summary>
        internal static string ma_sic {
            get {
                return ResourceManager.GetString("ma_sic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        internal static string ma_so_thue {
            get {
                return ResourceManager.GetString("ma_so_thue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế đã tạo trong dữ liệu doanh nghiệp.
        /// </summary>
        internal static string ma_so_thue_da_tao_trong_du_lieu_doanh_nghiep {
            get {
                return ResourceManager.GetString("ma_so_thue_da_tao_trong_du_lieu_doanh_nghiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mất khách hàng.
        /// </summary>
        internal static string mat_khach_hang {
            get {
                return ResourceManager.GetString("mat_khach_hang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string mat_khau {
            get {
                return ResourceManager.GetString("mat_khau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng.
        /// </summary>
        internal static string mat_khau_cu_khong_dung {
            get {
                return ResourceManager.GetString("mat_khau_cu_khong_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không đúng.
        /// </summary>
        internal static string mat_khau_khong_dung {
            get {
                return ResourceManager.GetString("mat_khau_khong_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được để trống.
        /// </summary>
        internal static string mat_khau_khong_duoc_de_trong {
            get {
                return ResourceManager.GetString("mat_khau_khong_duoc_de_trong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mặt sau CMND.
        /// </summary>
        internal static string mat_sau_cmnd {
            get {
                return ResourceManager.GetString("mat_sau_cmnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mặt trước CMND.
        /// </summary>
        internal static string mat_truoc_cmnd {
            get {
                return ResourceManager.GetString("mat_truoc_cmnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string mo_ta {
            get {
                return ResourceManager.GetString("mo_ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả (EN).
        /// </summary>
        internal static string mo_ta_en {
            get {
                return ResourceManager.GetString("mo_ta_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả (VN).
        /// </summary>
        internal static string mo_ta_vn {
            get {
                return ResourceManager.GetString("mo_ta_vn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm sinh âm lịch.
        /// </summary>
        internal static string nam_sinh_am_lich {
            get {
                return ResourceManager.GetString("nam_sinh_am_lich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu hiệu lực.
        /// </summary>
        internal static string ngay_bat_dau_hieu_luc {
            get {
                return ResourceManager.GetString("ngay_bat_dau_hieu_luc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp.
        /// </summary>
        internal static string ngay_cap {
            get {
                return ResourceManager.GetString("ngay_cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cuối.
        /// </summary>
        internal static string ngay_cuoi {
            get {
                return ResourceManager.GetString("ngay_cuoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hiệu lực.
        /// </summary>
        internal static string ngay_het_hieu_luc {
            get {
                return ResourceManager.GetString("ngay_het_hieu_luc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        internal static string ngay_sinh {
            get {
                return ResourceManager.GetString("ngay_sinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngũ hành.
        /// </summary>
        internal static string ngu_hanh {
            get {
                return ResourceManager.GetString("ngu_hanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người đại diện.
        /// </summary>
        internal static string nguoi_dai_dien {
            get {
                return ResourceManager.GetString("nguoi_dai_dien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người liên quan.
        /// </summary>
        internal static string nguoi_lien_quan {
            get {
                return ResourceManager.GetString("nguoi_lien_quan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tham dự bắt buộc.
        /// </summary>
        internal static string nguoi_tham_du_bat_buoc {
            get {
                return ResourceManager.GetString("nguoi_tham_du_bat_buoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tham dự không bắt buộc.
        /// </summary>
        internal static string nguoi_tham_du_khong_bat_buoc {
            get {
                return ResourceManager.GetString("nguoi_tham_du_khong_bat_buoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người Ủy Quyền.
        /// </summary>
        internal static string nguoi_uy_quyen {
            get {
                return ResourceManager.GetString("nguoi_uy_quyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguồn khách hàng.
        /// </summary>
        internal static string nguon_khach_hang {
            get {
                return ResourceManager.GetString("nguon_khach_hang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhắn tin.
        /// </summary>
        internal static string nhan_tin {
            get {
                return ResourceManager.GetString("nhan_tin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập chức vụ.
        /// </summary>
        internal static string nhap_chuc_vu {
            get {
                return ResourceManager.GetString("nhap_chuc_vu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập doanh thu mỗi năm.
        /// </summary>
        internal static string nhap_doanh_thu_moi_nam {
            get {
                return ResourceManager.GetString("nhap_doanh_thu_moi_nam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập email.
        /// </summary>
        internal static string nhap_email {
            get {
                return ResourceManager.GetString("nhap_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập email 2.
        /// </summary>
        internal static string nhap_email_2 {
            get {
                return ResourceManager.GetString("nhap_email_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập fax của công ty.
        /// </summary>
        internal static string nhap_fax_cua_cong_ty {
            get {
                return ResourceManager.GetString("nhap_fax_cua_cong_ty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập họ tên.
        /// </summary>
        internal static string nhap_ho_ten {
            get {
                return ResourceManager.GetString("nhap_ho_ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã SIC.
        /// </summary>
        internal static string nhap_ma_sic {
            get {
                return ResourceManager.GetString("nhap_ma_sic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã số thuế.
        /// </summary>
        internal static string nhap_ma_so_thue {
            get {
                return ResourceManager.GetString("nhap_ma_so_thue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mô tả.
        /// </summary>
        internal static string nhap_mo_ta {
            get {
                return ResourceManager.GetString("nhap_mo_ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nơi cấp.
        /// </summary>
        internal static string nhap_noi_cap {
            get {
                return ResourceManager.GetString("nhap_noi_cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số điện thoại.
        /// </summary>
        internal static string nhap_sdt {
            get {
                return ResourceManager.GetString("nhap_sdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số điện thoại công ty.
        /// </summary>
        internal static string nhap_sdt_cong_ty {
            get {
                return ResourceManager.GetString("nhap_sdt_cong_ty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số điện thoại kinh doanh.
        /// </summary>
        internal static string nhap_sdt_kinh_doanh {
            get {
                return ResourceManager.GetString("nhap_sdt_kinh_doanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số CMND.
        /// </summary>
        internal static string nhap_so_cmnd {
            get {
                return ResourceManager.GetString("nhap_so_cmnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số giấy phép kinh doanh.
        /// </summary>
        internal static string nhap_so_giay_phep_kinh_doanh {
            get {
                return ResourceManager.GetString("nhap_so_giay_phep_kinh_doanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số hộ chiếu.
        /// </summary>
        internal static string nhap_so_ho_chieu {
            get {
                return ResourceManager.GetString("nhap_so_ho_chieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số lượng nhân viên.
        /// </summary>
        internal static string nhap_so_luong_nhan_vien {
            get {
                return ResourceManager.GetString("nhap_so_luong_nhan_vien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số thẻ căn cước.
        /// </summary>
        internal static string nhap_so_the_can_cuoc {
            get {
                return ResourceManager.GetString("nhap_so_the_can_cuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên công ty.
        /// </summary>
        internal static string nhap_ten_cong_ty {
            get {
                return ResourceManager.GetString("nhap_ten_cong_ty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên công ty (khác).
        /// </summary>
        internal static string nhap_ten_cong_ty_khac {
            get {
                return ResourceManager.GetString("nhap_ten_cong_ty_khac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên viết tắt.
        /// </summary>
        internal static string nhap_ten_viet_tat {
            get {
                return ResourceManager.GetString("nhap_ten_viet_tat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tiêu đề.
        /// </summary>
        internal static string nhap_tieu_de {
            get {
                return ResourceManager.GetString("nhap_tieu_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập website.
        /// </summary>
        internal static string nhap_website {
            get {
                return ResourceManager.GetString("nhap_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm:.
        /// </summary>
        internal static string nhom_ {
            get {
                return ResourceManager.GetString("nhom_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm khách hàng.
        /// </summary>
        internal static string nhom_khach_hang {
            get {
                return ResourceManager.GetString("nhom_khach_hang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi cấp.
        /// </summary>
        internal static string noi_cap {
            get {
                return ResourceManager.GetString("noi_cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password không được chứa ký tự khoảng trắng.
        /// </summary>
        internal static string password_khong_duoc_chua_ky_tu_khoang_trang {
            get {
                return ResourceManager.GetString("password_khong_duoc_chua_ky_tu_khoang_trang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phản hồi.
        /// </summary>
        internal static string phan_hoi_appshell {
            get {
                return ResourceManager.GetString("phan_hoi_appshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phong Thủy.
        /// </summary>
        internal static string phong_thuy {
            get {
                return ResourceManager.GetString("phong_thuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualify Account thành công, Qualify Contact thất bại.
        /// </summary>
        internal static string qualify_account_thanh_cong_qualify_contact_that_bai {
            get {
                return ResourceManager.GetString("qualify_account_thanh_cong_qualify_contact_that_bai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualify Contact thành công, Qualify Account thất bại.
        /// </summary>
        internal static string qualify_contact_thanh_cong_qualify_account_that_bai {
            get {
                return ResourceManager.GetString("qualify_contact_thanh_cong_qualify_account_that_bai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quẻ mệnh.
        /// </summary>
        internal static string que_menh {
            get {
                return ResourceManager.GetString("que_menh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc tịch.
        /// </summary>
        internal static string quoc_tich {
            get {
                return ResourceManager.GetString("quoc_tich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm:.
        /// </summary>
        internal static string san_pham_ {
            get {
                return ResourceManager.GetString("san_pham_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        internal static string sdt {
            get {
                return ResourceManager.GetString("sdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại:.
        /// </summary>
        internal static string sdt_ {
            get {
                return ResourceManager.GetString("sdt_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SĐT công ty.
        /// </summary>
        internal static string sdt_cong_ty {
            get {
                return ResourceManager.GetString("sdt_cong_ty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SĐT kinh doanh.
        /// </summary>
        internal static string sdt_kinh_doanh {
            get {
                return ResourceManager.GetString("sdt_kinh_doanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại sai định dạng. Vui lòng kiểm tra lại.
        /// </summary>
        internal static string sdt_sai_dinh_dang_vui_long_kiem_tra_lai {
            get {
                return ResourceManager.GetString("sdt_sai_dinh_dang_vui_long_kiem_tra_lai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND.
        /// </summary>
        internal static string so_cmnd {
            get {
                return ResourceManager.GetString("so_cmnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND đã được sử dụng.
        /// </summary>
        internal static string so_cmnd_da_duoc_su_dung {
            get {
                return ResourceManager.GetString("so_cmnd_da_duoc_su_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số giấy phép kinh doanh đã tạo trong dữ liệu doanh nghiệp.
        /// </summary>
        internal static string so_giay_phep_kinh_doanh_da_tao_trong_du_lieu_doanh_nghiep {
            get {
                return ResourceManager.GetString("so_giay_phep_kinh_doanh_da_tao_trong_du_lieu_doanh_nghiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hộ chiếu.
        /// </summary>
        internal static string so_ho_chieu {
            get {
                return ResourceManager.GetString("so_ho_chieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hộ chiếu đã được sử dụng.
        /// </summary>
        internal static string so_ho_chieu_da_duoc_su_dung {
            get {
                return ResourceManager.GetString("so_ho_chieu_da_duoc_su_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng nhân viên.
        /// </summary>
        internal static string so_luong_nhan_vien {
            get {
                return ResourceManager.GetString("so_luong_nhan_vien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thẻ căn cước.
        /// </summary>
        internal static string so_the_can_cuoc {
            get {
                return ResourceManager.GetString("so_the_can_cuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sự kiện cả ngày.
        /// </summary>
        internal static string su_kien_ca_ngay {
            get {
                return ResourceManager.GetString("su_kien_ca_ngay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu kinh doanh.
        /// </summary>
        internal static string tai_lieu_kinh_doanh_appshell {
            get {
                return ResourceManager.GetString("tai_lieu_kinh_doanh_appshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo khách hàng.
        /// </summary>
        internal static string tao_khach_hang {
            get {
                return ResourceManager.GetString("tao_khach_hang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Mới KH Cá Nhân.
        /// </summary>
        internal static string tao_moi_khach_hang_ca_nhan_title {
            get {
                return ResourceManager.GetString("tao_moi_khach_hang_ca_nhan_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Mới KH Doanh Nghiệp.
        /// </summary>
        internal static string tao_moi_khach_hang_doanh_nghiep_title {
            get {
                return ResourceManager.GetString("tao_moi_khach_hang_doanh_nghiep_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Mới KH Tiềm Năng.
        /// </summary>
        internal static string tao_moi_khach_hang_tiem_nang_title {
            get {
                return ResourceManager.GetString("tao_moi_khach_hang_tiem_nang_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới thành công.
        /// </summary>
        internal static string tao_moi_thanh_cong {
            get {
                return ResourceManager.GetString("tao_moi_thanh_cong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên công ty.
        /// </summary>
        internal static string ten_cong_ty {
            get {
                return ResourceManager.GetString("ten_cong_ty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên công ty :.
        /// </summary>
        internal static string ten_cong_ty_ {
            get {
                return ResourceManager.GetString("ten_cong_ty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên công ty (khác).
        /// </summary>
        internal static string ten_cong_ty_khac {
            get {
                return ResourceManager.GetString("ten_cong_ty_khac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        internal static string ten_dang_nhap {
            get {
                return ResourceManager.GetString("ten_dang_nhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không đúng.
        /// </summary>
        internal static string ten_dang_nhap_khong_dung {
            get {
                return ResourceManager.GetString("ten_dang_nhap_khong_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không được để trống.
        /// </summary>
        internal static string ten_dang_nhap_khong_duoc_de_trong {
            get {
                return ResourceManager.GetString("ten_dang_nhap_khong_duoc_de_trong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên viết tắt.
        /// </summary>
        internal static string ten_viet_tat {
            get {
                return ResourceManager.GetString("ten_viet_tat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        internal static string thanh_cong {
            get {
                return ResourceManager.GetString("thanh_cong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thất bại.
        /// </summary>
        internal static string that_bai {
            get {
                return ResourceManager.GetString("that_bai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Công việc.
        /// </summary>
        internal static string them_cong_viec {
            get {
                return ResourceManager.GetString("them_cong_viec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Cuộc gọi.
        /// </summary>
        internal static string them_cuoc_goi {
            get {
                return ResourceManager.GetString("them_cuoc_goi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Cuộc họp.
        /// </summary>
        internal static string them_cuoc_hop {
            get {
                return ResourceManager.GetString("them_cuoc_hop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Người ủy quyền.
        /// </summary>
        internal static string them_nguoi_uy_quyen {
            get {
                return ResourceManager.GetString("them_nguoi_uy_quyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian:.
        /// </summary>
        internal static string thoi_gian_ {
            get {
                return ResourceManager.GetString("thoi_gian_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian bắt đầu.
        /// </summary>
        internal static string thoi_gian_bat_dau {
            get {
                return ResourceManager.GetString("thoi_gian_bat_dau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian bắt đầu:.
        /// </summary>
        internal static string thoi_gian_bat_dau_ {
            get {
                return ResourceManager.GetString("thoi_gian_bat_dau_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian hết hạn:.
        /// </summary>
        internal static string thoi_gian_het_han_ {
            get {
                return ResourceManager.GetString("thoi_gian_het_han_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian kết thúc.
        /// </summary>
        internal static string thoi_gian_ket_thuc {
            get {
                return ResourceManager.GetString("thoi_gian_ket_thuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian kết thúc:.
        /// </summary>
        internal static string thoi_gian_ket_thuc_ {
            get {
                return ResourceManager.GetString("thoi_gian_ket_thuc_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string thong_bao {
            get {
                return ResourceManager.GetString("thong_bao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin.
        /// </summary>
        internal static string thong_tin {
            get {
                return ResourceManager.GetString("thong_tin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin Chi Tiết.
        /// </summary>
        internal static string thong_tin_chi_tiet {
            get {
                return ResourceManager.GetString("thong_tin_chi_tiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin CMND/Hộ Chiếu.
        /// </summary>
        internal static string thong_tin_cmnd_ho_chieu {
            get {
                return ResourceManager.GetString("thong_tin_cmnd_ho_chieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin Cơ Bản.
        /// </summary>
        internal static string thong_tin_co_ban {
            get {
                return ResourceManager.GetString("thong_tin_co_ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin Công Ty.
        /// </summary>
        internal static string thong_tin_cong_ty {
            get {
                return ResourceManager.GetString("thong_tin_cong_ty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin Gia Chủ.
        /// </summary>
        internal static string thong_tin_gia_chu {
            get {
                return ResourceManager.GetString("thong_tin_gia_chu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin khách hàng.
        /// </summary>
        internal static string thong_tin_khach_hang {
            get {
                return ResourceManager.GetString("thong_tin_khach_hang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư viện.
        /// </summary>
        internal static string thu_vien {
            get {
                return ResourceManager.GetString("thu_vien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiềm năng.
        /// </summary>
        internal static string tiem_nang {
            get {
                return ResourceManager.GetString("tiem_nang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        internal static string tieu_de {
            get {
                return ResourceManager.GetString("tieu_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng:.
        /// </summary>
        internal static string tinh_trang_ {
            get {
                return ResourceManager.GetString("tinh_trang_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền.
        /// </summary>
        internal static string tong_tien {
            get {
                return ResourceManager.GetString("tong_tien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền:.
        /// </summary>
        internal static string tong_tien_ {
            get {
                return ResourceManager.GetString("tong_tien_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string trang_chu_appshell {
            get {
                return ResourceManager.GetString("trang_chu_appshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuỳ chọn.
        /// </summary>
        internal static string tuy_chon {
            get {
                return ResourceManager.GetString("tuy_chon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn địa chỉ liên lạc.
        /// </summary>
        internal static string vui_long_chon_dia_chi_lien_lac {
            get {
                return ResourceManager.GetString("vui_long_chon_dia_chi_lien_lac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn địa chỉ thường trú.
        /// </summary>
        internal static string vui_long_chon_dia_chi_thuong_tru {
            get {
                return ResourceManager.GetString("vui_long_chon_dia_chi_thuong_tru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn giới tính.
        /// </summary>
        internal static string vui_long_chon_gioi_tinh {
            get {
                return ResourceManager.GetString("vui_long_chon_gioi_tinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn loại khách hàng.
        /// </summary>
        internal static string vui_long_chon_loai_khach_hang {
            get {
                return ResourceManager.GetString("vui_long_chon_loai_khach_hang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ngày sinh.
        /// </summary>
        internal static string vui_long_chon_ngay_sinh {
            get {
                return ResourceManager.GetString("vui_long_chon_ngay_sinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn người đại diện.
        /// </summary>
        internal static string vui_long_chon_nguoi_dai_dien {
            get {
                return ResourceManager.GetString("vui_long_chon_nguoi_dai_dien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập họ tên.
        /// </summary>
        internal static string vui_long_nhap_ho_ten {
            get {
                return ResourceManager.GetString("vui_long_nhap_ho_ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu cũ.
        /// </summary>
        internal static string vui_long_nhap_mat_khau_cu {
            get {
                return ResourceManager.GetString("vui_long_nhap_mat_khau_cu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu mới.
        /// </summary>
        internal static string vui_long_nhap_mat_khau_moi {
            get {
                return ResourceManager.GetString("vui_long_nhap_mat_khau_moi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập password nhiều hơn 6 ký tự.
        /// </summary>
        internal static string vui_long_nhap_password_nhieu_hon_6_ky_tu {
            get {
                return ResourceManager.GetString("vui_long_nhap_password_nhieu_hon_6_ky_tu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số điện thoại.
        /// </summary>
        internal static string vui_long_nhap_sdt {
            get {
                return ResourceManager.GetString("vui_long_nhap_sdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số điện thoại công ty.
        /// </summary>
        internal static string vui_long_nhap_sdt_cong_ty {
            get {
                return ResourceManager.GetString("vui_long_nhap_sdt_cong_ty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số CMND.
        /// </summary>
        internal static string vui_long_nhap_so_cmnd {
            get {
                return ResourceManager.GetString("vui_long_nhap_so_cmnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số giấy phép kinh doanh.
        /// </summary>
        internal static string vui_long_nhap_so_giay_phep_kinh_doanh {
            get {
                return ResourceManager.GetString("vui_long_nhap_so_giay_phep_kinh_doanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số nhà/đường/phường.
        /// </summary>
        internal static string vui_long_nhap_so_nha_duong_phuong {
            get {
                return ResourceManager.GetString("vui_long_nhap_so_nha_duong_phuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên công ty.
        /// </summary>
        internal static string vui_long_nhap_ten_cong_ty {
            get {
                return ResourceManager.GetString("vui_long_nhap_ten_cong_ty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tiêu đề.
        /// </summary>
        internal static string vui_long_nhap_tieu_de {
            get {
                return ResourceManager.GetString("vui_long_nhap_tieu_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập xác nhận mật khẩu mới.
        /// </summary>
        internal static string vui_long_nhap_xac_nhan_mat_khau_moi {
            get {
                return ResourceManager.GetString("vui_long_nhap_xac_nhan_mat_khau_moi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        internal static string xac_nhan {
            get {
                return ResourceManager.GetString("xac_nhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu không đúng.
        /// </summary>
        internal static string xac_nhan_mat_khau_khong_dung {
            get {
                return ResourceManager.GetString("xac_nhan_mat_khau_khong_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem ảnh mặt sau CMND.
        /// </summary>
        internal static string xem_anh_mat_sau_cmnd {
            get {
                return ResourceManager.GetString("xem_anh_mat_sau_cmnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem ảnh mặt trước CMND.
        /// </summary>
        internal static string xem_anh_mat_truoc_cmnd {
            get {
                return ResourceManager.GetString("xem_anh_mat_truoc_cmnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        internal static string xem_them {
            get {
                return ResourceManager.GetString("xem_them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa người ủy quyền thất bại.
        /// </summary>
        internal static string xoa_nguoi_uy_quyen_that_bai {
            get {
                return ResourceManager.GetString("xoa_nguoi_uy_quyen_that_bai", resourceCulture);
            }
        }
    }
}
