//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConasiCRM.Portable.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_vn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_vn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConasiCRM.Portable.Resources.Language_vn", typeof(Language_vn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đang sử dụng mật khẩu cũ. Vui lòng nhập lại.
        /// </summary>
        internal static string ban_dang_su_dung_mat_khau_cu_vui_long_nhap_lai {
            get {
                return ResourceManager.GetString("ban_dang_su_dung_mat_khau_cu_vui_long_nhap_lai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        internal static string cap_nhat_thanh_cong {
            get {
                return ResourceManager.GetString("cap_nhat_thanh_cong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thất bại.
        /// </summary>
        internal static string cap_nhat_that_bai {
            get {
                return ResourceManager.GetString("cap_nhat_that_bai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chụp hình.
        /// </summary>
        internal static string chup_hinh {
            get {
                return ResourceManager.GetString("chup_hinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string dang_nhap {
            get {
                return ResourceManager.GetString("dang_nhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công.
        /// </summary>
        internal static string doi_mat_khau_thanh_cong {
            get {
                return ResourceManager.GetString("doi_mat_khau_thanh_cong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thất bại.
        /// </summary>
        internal static string doi_mat_khau_that_bai {
            get {
                return ResourceManager.GetString("doi_mat_khau_that_bai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        internal static string dong {
            get {
                return ResourceManager.GetString("dong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhớ đăng nhập.
        /// </summary>
        internal static string ghi_nho_dang_nhap {
            get {
                return ResourceManager.GetString("ghi_nho_dang_nhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string huy {
            get {
                return ResourceManager.GetString("huy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không cập nhật được thông tin Imei.
        /// </summary>
        internal static string khong_cap_nhat_duoc_thong_tin_imei {
            get {
                return ResourceManager.GetString("khong_cap_nhat_duoc_thong_tin_imei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy user.
        /// </summary>
        internal static string khong_tim_thay_user {
            get {
                return ResourceManager.GetString("khong_tim_thay_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kết nối đến Server.
        /// </summary>
        internal static string loi_ket_noi_den_server {
            get {
                return ResourceManager.GetString("loi_ket_noi_den_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string mat_khau {
            get {
                return ResourceManager.GetString("mat_khau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng.
        /// </summary>
        internal static string mat_khau_cu_khong_dung {
            get {
                return ResourceManager.GetString("mat_khau_cu_khong_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không đúng.
        /// </summary>
        internal static string mat_khau_khong_dung {
            get {
                return ResourceManager.GetString("mat_khau_khong_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được để trống.
        /// </summary>
        internal static string mat_khau_khong_duoc_de_trong {
            get {
                return ResourceManager.GetString("mat_khau_khong_duoc_de_trong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password không được chứa ký tự khoảng trắng.
        /// </summary>
        internal static string password_khong_duoc_chua_ky_tu_khoang_trang {
            get {
                return ResourceManager.GetString("password_khong_duoc_chua_ky_tu_khoang_trang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        internal static string ten_dang_nhap {
            get {
                return ResourceManager.GetString("ten_dang_nhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không đúng.
        /// </summary>
        internal static string ten_dang_nhap_khong_dung {
            get {
                return ResourceManager.GetString("ten_dang_nhap_khong_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không được để trống.
        /// </summary>
        internal static string ten_dang_nhap_khong_duoc_de_trong {
            get {
                return ResourceManager.GetString("ten_dang_nhap_khong_duoc_de_trong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string thong_bao {
            get {
                return ResourceManager.GetString("thong_bao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư viện.
        /// </summary>
        internal static string thu_vien {
            get {
                return ResourceManager.GetString("thu_vien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuỳ chọn.
        /// </summary>
        internal static string tuy_chon {
            get {
                return ResourceManager.GetString("tuy_chon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn giới tính.
        /// </summary>
        internal static string vui_long_chon_gioi_tinh {
            get {
                return ResourceManager.GetString("vui_long_chon_gioi_tinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ngày sinh.
        /// </summary>
        internal static string vui_long_chon_ngay_sinh {
            get {
                return ResourceManager.GetString("vui_long_chon_ngay_sinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu cũ.
        /// </summary>
        internal static string vui_long_nhap_mat_khau_cu {
            get {
                return ResourceManager.GetString("vui_long_nhap_mat_khau_cu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu mới.
        /// </summary>
        internal static string vui_long_nhap_mat_khau_moi {
            get {
                return ResourceManager.GetString("vui_long_nhap_mat_khau_moi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập password nhiều hơn 6 ký tự.
        /// </summary>
        internal static string vui_long_nhap_password_nhieu_hon_6_ky_tu {
            get {
                return ResourceManager.GetString("vui_long_nhap_password_nhieu_hon_6_ky_tu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số điện thoại.
        /// </summary>
        internal static string vui_long_nhap_so_dien_thoai {
            get {
                return ResourceManager.GetString("vui_long_nhap_so_dien_thoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số nhà/đường/phường.
        /// </summary>
        internal static string vui_long_nhap_so_nha_duong_phuong {
            get {
                return ResourceManager.GetString("vui_long_nhap_so_nha_duong_phuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập xác nhận mật khẩu mới.
        /// </summary>
        internal static string vui_long_nhap_xac_nhan_mat_khau_moi {
            get {
                return ResourceManager.GetString("vui_long_nhap_xac_nhan_mat_khau_moi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu không đúng.
        /// </summary>
        internal static string xac_nhan_mat_khau_khong_dung {
            get {
                return ResourceManager.GetString("xac_nhan_mat_khau_khong_dung", resourceCulture);
            }
        }
    }
}
