//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConasiCRM.Portable.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ConasiCRM.Portable.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string bang_tinh_gia_appshell {
            get {
                return ResourceManager.GetString("bang_tinh_gia_appshell", resourceCulture);
            }
        }
        
        internal static string ban_co_muon_xoa_nguoi_uy_quyen_nay_khong {
            get {
                return ResourceManager.GetString("ban_co_muon_xoa_nguoi_uy_quyen_nay_khong", resourceCulture);
            }
        }
        
        internal static string ban_dang_su_dung_mat_khau_cu_vui_long_nhap_lai {
            get {
                return ResourceManager.GetString("ban_dang_su_dung_mat_khau_cu_vui_long_nhap_lai", resourceCulture);
            }
        }
        
        internal static string cap_nhat {
            get {
                return ResourceManager.GetString("cap_nhat", resourceCulture);
            }
        }
        
        internal static string cap_nhat_khach_hang {
            get {
                return ResourceManager.GetString("cap_nhat_khach_hang", resourceCulture);
            }
        }
        
        internal static string cap_nhat_khach_hang_ca_nhan_title {
            get {
                return ResourceManager.GetString("cap_nhat_khach_hang_ca_nhan_title", resourceCulture);
            }
        }
        
        internal static string cap_nhat_khach_hang_doanh_nghiep_title {
            get {
                return ResourceManager.GetString("cap_nhat_khach_hang_doanh_nghiep_title", resourceCulture);
            }
        }
        
        internal static string cap_nhat_khach_hang_tiem_nang_title {
            get {
                return ResourceManager.GetString("cap_nhat_khach_hang_tiem_nang_title", resourceCulture);
            }
        }
        
        internal static string cap_nhat_thanh_cong {
            get {
                return ResourceManager.GetString("cap_nhat_thanh_cong", resourceCulture);
            }
        }
        
        internal static string cap_nhat_that_bai {
            get {
                return ResourceManager.GetString("cap_nhat_that_bai", resourceCulture);
            }
        }
        
        internal static string ca_nhan {
            get {
                return ResourceManager.GetString("ca_nhan", resourceCulture);
            }
        }
        
        internal static string cham_soc_khach_hang {
            get {
                return ResourceManager.GetString("cham_soc_khach_hang", resourceCulture);
            }
        }
        
        internal static string chien_dich {
            get {
                return ResourceManager.GetString("chien_dich", resourceCulture);
            }
        }
        
        internal static string chinh_sua {
            get {
                return ResourceManager.GetString("chinh_sua", resourceCulture);
            }
        }
        
        internal static string chon_anh_tu_thu_vien {
            get {
                return ResourceManager.GetString("chon_anh_tu_thu_vien", resourceCulture);
            }
        }
        
        internal static string chon_chien_dich {
            get {
                return ResourceManager.GetString("chon_chien_dich", resourceCulture);
            }
        }
        
        internal static string chon_cong_ty {
            get {
                return ResourceManager.GetString("chon_cong_ty", resourceCulture);
            }
        }
        
        internal static string chon_danh_gia {
            get {
                return ResourceManager.GetString("chon_danh_gia", resourceCulture);
            }
        }
        
        internal static string chon_dia_chi_cong_ty {
            get {
                return ResourceManager.GetString("chon_dia_chi_cong_ty", resourceCulture);
            }
        }
        
        internal static string chon_dia_chi_lien_lac {
            get {
                return ResourceManager.GetString("chon_dia_chi_lien_lac", resourceCulture);
            }
        }
        
        internal static string chon_dia_chi_thuong_tru {
            get {
                return ResourceManager.GetString("chon_dia_chi_thuong_tru", resourceCulture);
            }
        }
        
        internal static string chon_dia_chi_tru_so_chinh {
            get {
                return ResourceManager.GetString("chon_dia_chi_tru_so_chinh", resourceCulture);
            }
        }
        
        internal static string chon_gioi_tinh {
            get {
                return ResourceManager.GetString("chon_gioi_tinh", resourceCulture);
            }
        }
        
        internal static string chon_linh_vuc {
            get {
                return ResourceManager.GetString("chon_linh_vuc", resourceCulture);
            }
        }
        
        internal static string chon_loai_khach_hang {
            get {
                return ResourceManager.GetString("chon_loai_khach_hang", resourceCulture);
            }
        }
        
        internal static string chon_ngay_cap {
            get {
                return ResourceManager.GetString("chon_ngay_cap", resourceCulture);
            }
        }
        
        internal static string chon_ngay_sinh {
            get {
                return ResourceManager.GetString("chon_ngay_sinh", resourceCulture);
            }
        }
        
        internal static string chon_nguoi_dai_dien {
            get {
                return ResourceManager.GetString("chon_nguoi_dai_dien", resourceCulture);
            }
        }
        
        internal static string chon_nguon_khach_hang {
            get {
                return ResourceManager.GetString("chon_nguon_khach_hang", resourceCulture);
            }
        }
        
        internal static string chon_quoc_tich {
            get {
                return ResourceManager.GetString("chon_quoc_tich", resourceCulture);
            }
        }
        
        internal static string chua_co_contact_khong_the_chinh_sua_thong_tin {
            get {
                return ResourceManager.GetString("chua_co_contact_khong_the_chinh_sua_thong_tin", resourceCulture);
            }
        }
        
        internal static string chuc_vu {
            get {
                return ResourceManager.GetString("chuc_vu", resourceCulture);
            }
        }
        
        internal static string chuc_vu_en {
            get {
                return ResourceManager.GetString("chuc_vu_en", resourceCulture);
            }
        }
        
        internal static string chuc_vu_vn {
            get {
                return ResourceManager.GetString("chuc_vu_vn", resourceCulture);
            }
        }
        
        internal static string chup_hinh {
            get {
                return ResourceManager.GetString("chup_hinh", resourceCulture);
            }
        }
        
        internal static string chuyen_doi_khach_hang {
            get {
                return ResourceManager.GetString("chuyen_doi_khach_hang", resourceCulture);
            }
        }
        
        internal static string cong_ty {
            get {
                return ResourceManager.GetString("cong_ty", resourceCulture);
            }
        }
        
        internal static string cong_viec_da_duoc_huy {
            get {
                return ResourceManager.GetString("cong_viec_da_duoc_huy", resourceCulture);
            }
        }
        
        internal static string cong_viec_da_hoan_thanh {
            get {
                return ResourceManager.GetString("cong_viec_da_hoan_thanh", resourceCulture);
            }
        }
        
        internal static string cong_viec_hom_nay {
            get {
                return ResourceManager.GetString("cong_viec_hom_nay", resourceCulture);
            }
        }
        
        internal static string cong_viec_title {
            get {
                return ResourceManager.GetString("cong_viec_title", resourceCulture);
            }
        }
        
        internal static string cuoc_goi_da_duoc_huy {
            get {
                return ResourceManager.GetString("cuoc_goi_da_duoc_huy", resourceCulture);
            }
        }
        
        internal static string cuoc_goi_da_hoan_thanh {
            get {
                return ResourceManager.GetString("cuoc_goi_da_hoan_thanh", resourceCulture);
            }
        }
        
        internal static string cuoc_goi_title {
            get {
                return ResourceManager.GetString("cuoc_goi_title", resourceCulture);
            }
        }
        
        internal static string cuoc_hop_da_duoc_huy {
            get {
                return ResourceManager.GetString("cuoc_hop_da_duoc_huy", resourceCulture);
            }
        }
        
        internal static string cuoc_hop_da_hoan_thanh {
            get {
                return ResourceManager.GetString("cuoc_hop_da_hoan_thanh", resourceCulture);
            }
        }
        
        internal static string cuoc_hop_title {
            get {
                return ResourceManager.GetString("cuoc_hop_title", resourceCulture);
            }
        }
        
        internal static string dai_dien_ {
            get {
                return ResourceManager.GetString("dai_dien_", resourceCulture);
            }
        }
        
        internal static string dai_dien_phap_luat {
            get {
                return ResourceManager.GetString("dai_dien_phap_luat", resourceCulture);
            }
        }
        
        internal static string dang_nhap {
            get {
                return ResourceManager.GetString("dang_nhap", resourceCulture);
            }
        }
        
        internal static string dang_xuat_appshell {
            get {
                return ResourceManager.GetString("dang_xuat_appshell", resourceCulture);
            }
        }
        
        internal static string danh_gia {
            get {
                return ResourceManager.GetString("danh_gia", resourceCulture);
            }
        }
        
        internal static string danh_sach_theo_doi_appshell {
            get {
                return ResourceManager.GetString("danh_sach_theo_doi_appshell", resourceCulture);
            }
        }
        
        internal static string dat_coc {
            get {
                return ResourceManager.GetString("dat_coc", resourceCulture);
            }
        }
        
        internal static string dat_coc_appshell {
            get {
                return ResourceManager.GetString("dat_coc_appshell", resourceCulture);
            }
        }
        
        internal static string da_ban {
            get {
                return ResourceManager.GetString("da_ban", resourceCulture);
            }
        }
        
        internal static string da_chuyen_doi {
            get {
                return ResourceManager.GetString("da_chuyen_doi", resourceCulture);
            }
        }
        
        internal static string da_huy {
            get {
                return ResourceManager.GetString("da_huy", resourceCulture);
            }
        }
        
        internal static string da_nhan {
            get {
                return ResourceManager.GetString("da_nhan", resourceCulture);
            }
        }
        
        internal static string da_xay_ra_loi_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("da_xay_ra_loi_vui_long_thu_lai", resourceCulture);
            }
        }
        
        internal static string da_xoa_nguoi_uy_quyen_duoc_chon {
            get {
                return ResourceManager.GetString("da_xoa_nguoi_uy_quyen_duoc_chon", resourceCulture);
            }
        }
        
        internal static string dia_chi {
            get {
                return ResourceManager.GetString("dia_chi", resourceCulture);
            }
        }
        
        internal static string dia_chi_ {
            get {
                return ResourceManager.GetString("dia_chi_", resourceCulture);
            }
        }
        
        internal static string dia_chi_lien_lac {
            get {
                return ResourceManager.GetString("dia_chi_lien_lac", resourceCulture);
            }
        }
        
        internal static string dia_chi_lien_lac_ {
            get {
                return ResourceManager.GetString("dia_chi_lien_lac_", resourceCulture);
            }
        }
        
        internal static string dia_chi_thuong_tru {
            get {
                return ResourceManager.GetString("dia_chi_thuong_tru", resourceCulture);
            }
        }
        
        internal static string dia_chi_thuong_tru_ {
            get {
                return ResourceManager.GetString("dia_chi_thuong_tru_", resourceCulture);
            }
        }
        
        internal static string dia_chi_tru_so_chinh {
            get {
                return ResourceManager.GetString("dia_chi_tru_so_chinh", resourceCulture);
            }
        }
        
        internal static string dia_chi_tru_so_chinh_ {
            get {
                return ResourceManager.GetString("dia_chi_tru_so_chinh_", resourceCulture);
            }
        }
        
        internal static string dia_diem {
            get {
                return ResourceManager.GetString("dia_diem", resourceCulture);
            }
        }
        
        internal static string doanh_nghiep {
            get {
                return ResourceManager.GetString("doanh_nghiep", resourceCulture);
            }
        }
        
        internal static string doanh_thu_moi_nam {
            get {
                return ResourceManager.GetString("doanh_thu_moi_nam", resourceCulture);
            }
        }
        
        internal static string doi_mat_khau_thanh_cong {
            get {
                return ResourceManager.GetString("doi_mat_khau_thanh_cong", resourceCulture);
            }
        }
        
        internal static string doi_mat_khau_that_bai {
            get {
                return ResourceManager.GetString("doi_mat_khau_that_bai", resourceCulture);
            }
        }
        
        internal static string dong {
            get {
                return ResourceManager.GetString("dong", resourceCulture);
            }
        }
        
        internal static string dong_bo_danh_ba_appshell {
            get {
                return ResourceManager.GetString("dong_bo_danh_ba_appshell", resourceCulture);
            }
        }
        
        internal static string dong_y {
            get {
                return ResourceManager.GetString("dong_y", resourceCulture);
            }
        }
        
        internal static string don_vi_tien_te {
            get {
                return ResourceManager.GetString("don_vi_tien_te", resourceCulture);
            }
        }
        
        internal static string du_an_ {
            get {
                return ResourceManager.GetString("du_an_", resourceCulture);
            }
        }
        
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        internal static string email_ {
            get {
                return ResourceManager.GetString("email_", resourceCulture);
            }
        }
        
        internal static string email_2 {
            get {
                return ResourceManager.GetString("email_2", resourceCulture);
            }
        }
        
        internal static string email_2_sai_dinh_dang {
            get {
                return ResourceManager.GetString("email_2_sai_dinh_dang", resourceCulture);
            }
        }
        
        internal static string email_da_duoc_su_dung {
            get {
                return ResourceManager.GetString("email_da_duoc_su_dung", resourceCulture);
            }
        }
        
        internal static string email_sai_dinh_dang {
            get {
                return ResourceManager.GetString("email_sai_dinh_dang", resourceCulture);
            }
        }
        
        internal static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        internal static string ghi_nho_dang_nhap {
            get {
                return ResourceManager.GetString("ghi_nho_dang_nhap", resourceCulture);
            }
        }
        
        internal static string giao_dich {
            get {
                return ResourceManager.GetString("giao_dich", resourceCulture);
            }
        }
        
        internal static string giao_dich_home {
            get {
                return ResourceManager.GetString("giao_dich_home", resourceCulture);
            }
        }
        
        internal static string giay_phep_kinh_doanh {
            get {
                return ResourceManager.GetString("giay_phep_kinh_doanh", resourceCulture);
            }
        }
        
        internal static string gioi_tinh {
            get {
                return ResourceManager.GetString("gioi_tinh", resourceCulture);
            }
        }
        
        internal static string gio_hang_appshell {
            get {
                return ResourceManager.GetString("gio_hang_appshell", resourceCulture);
            }
        }
        
        internal static string giu_cho {
            get {
                return ResourceManager.GetString("giu_cho", resourceCulture);
            }
        }
        
        internal static string giu_cho_appshell {
            get {
                return ResourceManager.GetString("giu_cho_appshell", resourceCulture);
            }
        }
        
        internal static string goi_den {
            get {
                return ResourceManager.GetString("goi_den", resourceCulture);
            }
        }
        
        internal static string goi_dien {
            get {
                return ResourceManager.GetString("goi_dien", resourceCulture);
            }
        }
        
        internal static string goi_tu {
            get {
                return ResourceManager.GetString("goi_tu", resourceCulture);
            }
        }
        
        internal static string gui_tai_lieu_tiep_thi {
            get {
                return ResourceManager.GetString("gui_tai_lieu_tiep_thi", resourceCulture);
            }
        }
        
        internal static string hinh_chup_cmnd {
            get {
                return ResourceManager.GetString("hinh_chup_cmnd", resourceCulture);
            }
        }
        
        internal static string hoan_thanh {
            get {
                return ResourceManager.GetString("hoan_thanh", resourceCulture);
            }
        }
        
        internal static string hoat_dong_appshell {
            get {
                return ResourceManager.GetString("hoat_dong_appshell", resourceCulture);
            }
        }
        
        internal static string hoat_dong_title {
            get {
                return ResourceManager.GetString("hoat_dong_title", resourceCulture);
            }
        }
        
        internal static string hoa_hong {
            get {
                return ResourceManager.GetString("hoa_hong", resourceCulture);
            }
        }
        
        internal static string hom_nay_khong_co_cong_viec {
            get {
                return ResourceManager.GetString("hom_nay_khong_co_cong_viec", resourceCulture);
            }
        }
        
        internal static string hop_dong {
            get {
                return ResourceManager.GetString("hop_dong", resourceCulture);
            }
        }
        
        internal static string hop_dong_appshell {
            get {
                return ResourceManager.GetString("hop_dong_appshell", resourceCulture);
            }
        }
        
        internal static string ho_ten {
            get {
                return ResourceManager.GetString("ho_ten", resourceCulture);
            }
        }
        
        internal static string huong_tot {
            get {
                return ResourceManager.GetString("huong_tot", resourceCulture);
            }
        }
        
        internal static string huong_xau {
            get {
                return ResourceManager.GetString("huong_xau", resourceCulture);
            }
        }
        
        internal static string huy {
            get {
                return ResourceManager.GetString("huy", resourceCulture);
            }
        }
        
        internal static string khach_hang {
            get {
                return ResourceManager.GetString("khach_hang", resourceCulture);
            }
        }
        
        internal static string khach_hang_ {
            get {
                return ResourceManager.GetString("khach_hang_", resourceCulture);
            }
        }
        
        internal static string khach_hang_khong_co_sdt_vui_long_kiem_tra_lai {
            get {
                return ResourceManager.GetString("khach_hang_khong_co_sdt_vui_long_kiem_tra_lai", resourceCulture);
            }
        }
        
        internal static string khach_hang_moi {
            get {
                return ResourceManager.GetString("khach_hang_moi", resourceCulture);
            }
        }
        
        internal static string khach_hang_phai_tu_18_tuoi {
            get {
                return ResourceManager.GetString("khach_hang_phai_tu_18_tuoi", resourceCulture);
            }
        }
        
        internal static string khach_hang_tiem_nang {
            get {
                return ResourceManager.GetString("khach_hang_tiem_nang", resourceCulture);
            }
        }
        
        internal static string khong_cap_nhat_duoc_khach_hang_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("khong_cap_nhat_duoc_khach_hang_vui_long_thu_lai", resourceCulture);
            }
        }
        
        internal static string khong_cap_nhat_duoc_thong_tin_imei {
            get {
                return ResourceManager.GetString("khong_cap_nhat_duoc_thong_tin_imei", resourceCulture);
            }
        }
        
        internal static string khong_chuyen_doi {
            get {
                return ResourceManager.GetString("khong_chuyen_doi", resourceCulture);
            }
        }
        
        internal static string khong_co_du_lieu {
            get {
                return ResourceManager.GetString("khong_co_du_lieu", resourceCulture);
            }
        }
        
        internal static string khong_lien_he_duoc {
            get {
                return ResourceManager.GetString("khong_lien_he_duoc", resourceCulture);
            }
        }
        
        internal static string khong_load_duoc_chien_dich {
            get {
                return ResourceManager.GetString("khong_load_duoc_chien_dich", resourceCulture);
            }
        }
        
        internal static string khong_load_duoc_quan_huyen {
            get {
                return ResourceManager.GetString("khong_load_duoc_quan_huyen", resourceCulture);
            }
        }
        
        internal static string khong_load_duoc_quoc_gia {
            get {
                return ResourceManager.GetString("khong_load_duoc_quoc_gia", resourceCulture);
            }
        }
        
        internal static string khong_load_duoc_tinh_thanh {
            get {
                return ResourceManager.GetString("khong_load_duoc_tinh_thanh", resourceCulture);
            }
        }
        
        internal static string khong_quan_tam {
            get {
                return ResourceManager.GetString("khong_quan_tam", resourceCulture);
            }
        }
        
        internal static string khong_them_duoc_khach_hang_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("khong_them_duoc_khach_hang_vui_long_thu_lai", resourceCulture);
            }
        }
        
        internal static string khong_the_qualify {
            get {
                return ResourceManager.GetString("khong_the_qualify", resourceCulture);
            }
        }
        
        internal static string khong_tim_thay_thong_tin {
            get {
                return ResourceManager.GetString("khong_tim_thay_thong_tin", resourceCulture);
            }
        }
        
        internal static string khong_tim_thay_thong_tin_cong_ty {
            get {
                return ResourceManager.GetString("khong_tim_thay_thong_tin_cong_ty", resourceCulture);
            }
        }
        
        internal static string khong_tim_thay_thong_tin_khach_hang {
            get {
                return ResourceManager.GetString("khong_tim_thay_thong_tin_khach_hang", resourceCulture);
            }
        }
        
        internal static string khong_tim_thay_thong_tin_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("khong_tim_thay_thong_tin_vui_long_thu_lai", resourceCulture);
            }
        }
        
        internal static string khong_tim_thay_user {
            get {
                return ResourceManager.GetString("khong_tim_thay_user", resourceCulture);
            }
        }
        
        internal static string kich_hoat_lai_kh {
            get {
                return ResourceManager.GetString("kich_hoat_lai_kh", resourceCulture);
            }
        }
        
        internal static string la_ban_phong_thuy {
            get {
                return ResourceManager.GetString("la_ban_phong_thuy", resourceCulture);
            }
        }
        
        internal static string lich_lam_viec_appshell {
            get {
                return ResourceManager.GetString("lich_lam_viec_appshell", resourceCulture);
            }
        }
        
        internal static string linh_vuc {
            get {
                return ResourceManager.GetString("linh_vuc", resourceCulture);
            }
        }
        
        internal static string loai_ {
            get {
                return ResourceManager.GetString("loai_", resourceCulture);
            }
        }
        
        internal static string loai_khach_hang {
            get {
                return ResourceManager.GetString("loai_khach_hang", resourceCulture);
            }
        }
        
        internal static string loi_ket_noi_den_server {
            get {
                return ResourceManager.GetString("loi_ket_noi_den_server", resourceCulture);
            }
        }
        
        internal static string loi_khi_hoan_thanh_cong_viec_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("loi_khi_hoan_thanh_cong_viec_vui_long_thu_lai", resourceCulture);
            }
        }
        
        internal static string loi_khi_hoan_thanh_cuoc_goi_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("loi_khi_hoan_thanh_cuoc_goi_vui_long_thu_lai", resourceCulture);
            }
        }
        
        internal static string loi_khi_hoan_thanh_cuoc_hop_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("loi_khi_hoan_thanh_cuoc_hop_vui_long_thu_lai", resourceCulture);
            }
        }
        
        internal static string loi_khi_huy_cong_viec_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("loi_khi_huy_cong_viec_vui_long_thu_lai", resourceCulture);
            }
        }
        
        internal static string loi_khi_huy_cuoc_goi_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("loi_khi_huy_cuoc_goi_vui_long_thu_lai", resourceCulture);
            }
        }
        
        internal static string loi_khi_huy_cuoc_hop_vui_long_thu_lai {
            get {
                return ResourceManager.GetString("loi_khi_huy_cuoc_hop_vui_long_thu_lai", resourceCulture);
            }
        }
        
        internal static string mat_khach_hang {
            get {
                return ResourceManager.GetString("mat_khach_hang", resourceCulture);
            }
        }
        
        internal static string mat_khau {
            get {
                return ResourceManager.GetString("mat_khau", resourceCulture);
            }
        }
        
        internal static string mat_khau_cu_khong_dung {
            get {
                return ResourceManager.GetString("mat_khau_cu_khong_dung", resourceCulture);
            }
        }
        
        internal static string mat_khau_khong_dung {
            get {
                return ResourceManager.GetString("mat_khau_khong_dung", resourceCulture);
            }
        }
        
        internal static string mat_khau_khong_duoc_de_trong {
            get {
                return ResourceManager.GetString("mat_khau_khong_duoc_de_trong", resourceCulture);
            }
        }
        
        internal static string mat_sau_cmnd {
            get {
                return ResourceManager.GetString("mat_sau_cmnd", resourceCulture);
            }
        }
        
        internal static string mat_truoc_cmnd {
            get {
                return ResourceManager.GetString("mat_truoc_cmnd", resourceCulture);
            }
        }
        
        internal static string ma_sic {
            get {
                return ResourceManager.GetString("ma_sic", resourceCulture);
            }
        }
        
        internal static string ma_so_thue {
            get {
                return ResourceManager.GetString("ma_so_thue", resourceCulture);
            }
        }
        
        internal static string ma_so_thue_da_tao_trong_du_lieu_doanh_nghiep {
            get {
                return ResourceManager.GetString("ma_so_thue_da_tao_trong_du_lieu_doanh_nghiep", resourceCulture);
            }
        }
        
        internal static string mo_ta {
            get {
                return ResourceManager.GetString("mo_ta", resourceCulture);
            }
        }
        
        internal static string mo_ta_en {
            get {
                return ResourceManager.GetString("mo_ta_en", resourceCulture);
            }
        }
        
        internal static string mo_ta_vn {
            get {
                return ResourceManager.GetString("mo_ta_vn", resourceCulture);
            }
        }
        
        internal static string nam_sinh_am_lich {
            get {
                return ResourceManager.GetString("nam_sinh_am_lich", resourceCulture);
            }
        }
        
        internal static string ngay_bat_dau_hieu_luc {
            get {
                return ResourceManager.GetString("ngay_bat_dau_hieu_luc", resourceCulture);
            }
        }
        
        internal static string ngay_cap {
            get {
                return ResourceManager.GetString("ngay_cap", resourceCulture);
            }
        }
        
        internal static string ngay_cuoi {
            get {
                return ResourceManager.GetString("ngay_cuoi", resourceCulture);
            }
        }
        
        internal static string ngay_het_hieu_luc {
            get {
                return ResourceManager.GetString("ngay_het_hieu_luc", resourceCulture);
            }
        }
        
        internal static string ngay_sinh {
            get {
                return ResourceManager.GetString("ngay_sinh", resourceCulture);
            }
        }
        
        internal static string nguoi_dai_dien {
            get {
                return ResourceManager.GetString("nguoi_dai_dien", resourceCulture);
            }
        }
        
        internal static string nguoi_lien_quan {
            get {
                return ResourceManager.GetString("nguoi_lien_quan", resourceCulture);
            }
        }
        
        internal static string nguoi_tham_du_bat_buoc {
            get {
                return ResourceManager.GetString("nguoi_tham_du_bat_buoc", resourceCulture);
            }
        }
        
        internal static string nguoi_tham_du_khong_bat_buoc {
            get {
                return ResourceManager.GetString("nguoi_tham_du_khong_bat_buoc", resourceCulture);
            }
        }
        
        internal static string nguoi_uy_quyen {
            get {
                return ResourceManager.GetString("nguoi_uy_quyen", resourceCulture);
            }
        }
        
        internal static string nguon_khach_hang {
            get {
                return ResourceManager.GetString("nguon_khach_hang", resourceCulture);
            }
        }
        
        internal static string ngu_hanh {
            get {
                return ResourceManager.GetString("ngu_hanh", resourceCulture);
            }
        }
        
        internal static string nhan_tin {
            get {
                return ResourceManager.GetString("nhan_tin", resourceCulture);
            }
        }
        
        internal static string nhap_chuc_vu {
            get {
                return ResourceManager.GetString("nhap_chuc_vu", resourceCulture);
            }
        }
        
        internal static string nhap_doanh_thu_moi_nam {
            get {
                return ResourceManager.GetString("nhap_doanh_thu_moi_nam", resourceCulture);
            }
        }
        
        internal static string nhap_email {
            get {
                return ResourceManager.GetString("nhap_email", resourceCulture);
            }
        }
        
        internal static string nhap_email_2 {
            get {
                return ResourceManager.GetString("nhap_email_2", resourceCulture);
            }
        }
        
        internal static string nhap_fax_cua_cong_ty {
            get {
                return ResourceManager.GetString("nhap_fax_cua_cong_ty", resourceCulture);
            }
        }
        
        internal static string nhap_ho_ten {
            get {
                return ResourceManager.GetString("nhap_ho_ten", resourceCulture);
            }
        }
        
        internal static string nhap_ma_sic {
            get {
                return ResourceManager.GetString("nhap_ma_sic", resourceCulture);
            }
        }
        
        internal static string nhap_ma_so_thue {
            get {
                return ResourceManager.GetString("nhap_ma_so_thue", resourceCulture);
            }
        }
        
        internal static string nhap_mo_ta {
            get {
                return ResourceManager.GetString("nhap_mo_ta", resourceCulture);
            }
        }
        
        internal static string nhap_noi_cap {
            get {
                return ResourceManager.GetString("nhap_noi_cap", resourceCulture);
            }
        }
        
        internal static string nhap_sdt {
            get {
                return ResourceManager.GetString("nhap_sdt", resourceCulture);
            }
        }
        
        internal static string nhap_sdt_cong_ty {
            get {
                return ResourceManager.GetString("nhap_sdt_cong_ty", resourceCulture);
            }
        }
        
        internal static string nhap_sdt_kinh_doanh {
            get {
                return ResourceManager.GetString("nhap_sdt_kinh_doanh", resourceCulture);
            }
        }
        
        internal static string nhap_so_cmnd {
            get {
                return ResourceManager.GetString("nhap_so_cmnd", resourceCulture);
            }
        }
        
        internal static string nhap_so_giay_phep_kinh_doanh {
            get {
                return ResourceManager.GetString("nhap_so_giay_phep_kinh_doanh", resourceCulture);
            }
        }
        
        internal static string nhap_so_ho_chieu {
            get {
                return ResourceManager.GetString("nhap_so_ho_chieu", resourceCulture);
            }
        }
        
        internal static string nhap_so_luong_nhan_vien {
            get {
                return ResourceManager.GetString("nhap_so_luong_nhan_vien", resourceCulture);
            }
        }
        
        internal static string nhap_so_the_can_cuoc {
            get {
                return ResourceManager.GetString("nhap_so_the_can_cuoc", resourceCulture);
            }
        }
        
        internal static string nhap_ten_cong_ty {
            get {
                return ResourceManager.GetString("nhap_ten_cong_ty", resourceCulture);
            }
        }
        
        internal static string nhap_ten_cong_ty_khac {
            get {
                return ResourceManager.GetString("nhap_ten_cong_ty_khac", resourceCulture);
            }
        }
        
        internal static string nhap_ten_viet_tat {
            get {
                return ResourceManager.GetString("nhap_ten_viet_tat", resourceCulture);
            }
        }
        
        internal static string nhap_tieu_de {
            get {
                return ResourceManager.GetString("nhap_tieu_de", resourceCulture);
            }
        }
        
        internal static string nhap_website {
            get {
                return ResourceManager.GetString("nhap_website", resourceCulture);
            }
        }
        
        internal static string nhom_ {
            get {
                return ResourceManager.GetString("nhom_", resourceCulture);
            }
        }
        
        internal static string nhom_khach_hang {
            get {
                return ResourceManager.GetString("nhom_khach_hang", resourceCulture);
            }
        }
        
        internal static string noi_cap {
            get {
                return ResourceManager.GetString("noi_cap", resourceCulture);
            }
        }
        
        internal static string password_khong_duoc_chua_ky_tu_khoang_trang {
            get {
                return ResourceManager.GetString("password_khong_duoc_chua_ky_tu_khoang_trang", resourceCulture);
            }
        }
        
        internal static string phan_hoi_appshell {
            get {
                return ResourceManager.GetString("phan_hoi_appshell", resourceCulture);
            }
        }
        
        internal static string phong_thuy {
            get {
                return ResourceManager.GetString("phong_thuy", resourceCulture);
            }
        }
        
        internal static string qualify_account_thanh_cong_qualify_contact_that_bai {
            get {
                return ResourceManager.GetString("qualify_account_thanh_cong_qualify_contact_that_bai", resourceCulture);
            }
        }
        
        internal static string qualify_contact_thanh_cong_qualify_account_that_bai {
            get {
                return ResourceManager.GetString("qualify_contact_thanh_cong_qualify_account_that_bai", resourceCulture);
            }
        }
        
        internal static string que_menh {
            get {
                return ResourceManager.GetString("que_menh", resourceCulture);
            }
        }
        
        internal static string quoc_tich {
            get {
                return ResourceManager.GetString("quoc_tich", resourceCulture);
            }
        }
        
        internal static string san_pham_ {
            get {
                return ResourceManager.GetString("san_pham_", resourceCulture);
            }
        }
        
        internal static string sdt {
            get {
                return ResourceManager.GetString("sdt", resourceCulture);
            }
        }
        
        internal static string sdt_ {
            get {
                return ResourceManager.GetString("sdt_", resourceCulture);
            }
        }
        
        internal static string sdt_cong_ty {
            get {
                return ResourceManager.GetString("sdt_cong_ty", resourceCulture);
            }
        }
        
        internal static string sdt_kinh_doanh {
            get {
                return ResourceManager.GetString("sdt_kinh_doanh", resourceCulture);
            }
        }
        
        internal static string sdt_sai_dinh_dang_vui_long_kiem_tra_lai {
            get {
                return ResourceManager.GetString("sdt_sai_dinh_dang_vui_long_kiem_tra_lai", resourceCulture);
            }
        }
        
        internal static string so_cmnd {
            get {
                return ResourceManager.GetString("so_cmnd", resourceCulture);
            }
        }
        
        internal static string so_cmnd_da_duoc_su_dung {
            get {
                return ResourceManager.GetString("so_cmnd_da_duoc_su_dung", resourceCulture);
            }
        }
        
        internal static string so_giay_phep_kinh_doanh_da_tao_trong_du_lieu_doanh_nghiep {
            get {
                return ResourceManager.GetString("so_giay_phep_kinh_doanh_da_tao_trong_du_lieu_doanh_nghiep", resourceCulture);
            }
        }
        
        internal static string so_ho_chieu {
            get {
                return ResourceManager.GetString("so_ho_chieu", resourceCulture);
            }
        }
        
        internal static string so_ho_chieu_da_duoc_su_dung {
            get {
                return ResourceManager.GetString("so_ho_chieu_da_duoc_su_dung", resourceCulture);
            }
        }
        
        internal static string so_luong_nhan_vien {
            get {
                return ResourceManager.GetString("so_luong_nhan_vien", resourceCulture);
            }
        }
        
        internal static string so_the_can_cuoc {
            get {
                return ResourceManager.GetString("so_the_can_cuoc", resourceCulture);
            }
        }
        
        internal static string su_kien_ca_ngay {
            get {
                return ResourceManager.GetString("su_kien_ca_ngay", resourceCulture);
            }
        }
        
        internal static string tai_lieu_kinh_doanh_appshell {
            get {
                return ResourceManager.GetString("tai_lieu_kinh_doanh_appshell", resourceCulture);
            }
        }
        
        internal static string tao_khach_hang {
            get {
                return ResourceManager.GetString("tao_khach_hang", resourceCulture);
            }
        }
        
        internal static string tao_moi_khach_hang_ca_nhan_title {
            get {
                return ResourceManager.GetString("tao_moi_khach_hang_ca_nhan_title", resourceCulture);
            }
        }
        
        internal static string tao_moi_khach_hang_doanh_nghiep_title {
            get {
                return ResourceManager.GetString("tao_moi_khach_hang_doanh_nghiep_title", resourceCulture);
            }
        }
        
        internal static string tao_moi_khach_hang_tiem_nang_title {
            get {
                return ResourceManager.GetString("tao_moi_khach_hang_tiem_nang_title", resourceCulture);
            }
        }
        
        internal static string tao_moi_thanh_cong {
            get {
                return ResourceManager.GetString("tao_moi_thanh_cong", resourceCulture);
            }
        }
        
        internal static string ten_cong_ty {
            get {
                return ResourceManager.GetString("ten_cong_ty", resourceCulture);
            }
        }
        
        internal static string ten_cong_ty_ {
            get {
                return ResourceManager.GetString("ten_cong_ty_", resourceCulture);
            }
        }
        
        internal static string ten_cong_ty_khac {
            get {
                return ResourceManager.GetString("ten_cong_ty_khac", resourceCulture);
            }
        }
        
        internal static string ten_dang_nhap {
            get {
                return ResourceManager.GetString("ten_dang_nhap", resourceCulture);
            }
        }
        
        internal static string ten_dang_nhap_khong_dung {
            get {
                return ResourceManager.GetString("ten_dang_nhap_khong_dung", resourceCulture);
            }
        }
        
        internal static string ten_dang_nhap_khong_duoc_de_trong {
            get {
                return ResourceManager.GetString("ten_dang_nhap_khong_duoc_de_trong", resourceCulture);
            }
        }
        
        internal static string ten_viet_tat {
            get {
                return ResourceManager.GetString("ten_viet_tat", resourceCulture);
            }
        }
        
        internal static string thanh_cong {
            get {
                return ResourceManager.GetString("thanh_cong", resourceCulture);
            }
        }
        
        internal static string that_bai {
            get {
                return ResourceManager.GetString("that_bai", resourceCulture);
            }
        }
        
        internal static string them_cong_viec {
            get {
                return ResourceManager.GetString("them_cong_viec", resourceCulture);
            }
        }
        
        internal static string them_cuoc_goi {
            get {
                return ResourceManager.GetString("them_cuoc_goi", resourceCulture);
            }
        }
        
        internal static string them_cuoc_hop {
            get {
                return ResourceManager.GetString("them_cuoc_hop", resourceCulture);
            }
        }
        
        internal static string them_nguoi_uy_quyen {
            get {
                return ResourceManager.GetString("them_nguoi_uy_quyen", resourceCulture);
            }
        }
        
        internal static string thoi_gian_ {
            get {
                return ResourceManager.GetString("thoi_gian_", resourceCulture);
            }
        }
        
        internal static string thoi_gian_bat_dau {
            get {
                return ResourceManager.GetString("thoi_gian_bat_dau", resourceCulture);
            }
        }
        
        internal static string thoi_gian_bat_dau_ {
            get {
                return ResourceManager.GetString("thoi_gian_bat_dau_", resourceCulture);
            }
        }
        
        internal static string thoi_gian_het_han_ {
            get {
                return ResourceManager.GetString("thoi_gian_het_han_", resourceCulture);
            }
        }
        
        internal static string thoi_gian_ket_thuc {
            get {
                return ResourceManager.GetString("thoi_gian_ket_thuc", resourceCulture);
            }
        }
        
        internal static string thoi_gian_ket_thuc_ {
            get {
                return ResourceManager.GetString("thoi_gian_ket_thuc_", resourceCulture);
            }
        }
        
        internal static string thong_bao {
            get {
                return ResourceManager.GetString("thong_bao", resourceCulture);
            }
        }
        
        internal static string thong_tin {
            get {
                return ResourceManager.GetString("thong_tin", resourceCulture);
            }
        }
        
        internal static string thong_tin_chi_tiet {
            get {
                return ResourceManager.GetString("thong_tin_chi_tiet", resourceCulture);
            }
        }
        
        internal static string thong_tin_cmnd_ho_chieu {
            get {
                return ResourceManager.GetString("thong_tin_cmnd_ho_chieu", resourceCulture);
            }
        }
        
        internal static string thong_tin_cong_ty {
            get {
                return ResourceManager.GetString("thong_tin_cong_ty", resourceCulture);
            }
        }
        
        internal static string thong_tin_co_ban {
            get {
                return ResourceManager.GetString("thong_tin_co_ban", resourceCulture);
            }
        }
        
        internal static string thong_tin_gia_chu {
            get {
                return ResourceManager.GetString("thong_tin_gia_chu", resourceCulture);
            }
        }
        
        internal static string thong_tin_khach_hang {
            get {
                return ResourceManager.GetString("thong_tin_khach_hang", resourceCulture);
            }
        }
        
        internal static string thu_vien {
            get {
                return ResourceManager.GetString("thu_vien", resourceCulture);
            }
        }
        
        internal static string tiem_nang {
            get {
                return ResourceManager.GetString("tiem_nang", resourceCulture);
            }
        }
        
        internal static string tieu_de {
            get {
                return ResourceManager.GetString("tieu_de", resourceCulture);
            }
        }
        
        internal static string tinh_trang_ {
            get {
                return ResourceManager.GetString("tinh_trang_", resourceCulture);
            }
        }
        
        internal static string tong_tien {
            get {
                return ResourceManager.GetString("tong_tien", resourceCulture);
            }
        }
        
        internal static string tong_tien_ {
            get {
                return ResourceManager.GetString("tong_tien_", resourceCulture);
            }
        }
        
        internal static string trang_chu_appshell {
            get {
                return ResourceManager.GetString("trang_chu_appshell", resourceCulture);
            }
        }
        
        internal static string tuy_chon {
            get {
                return ResourceManager.GetString("tuy_chon", resourceCulture);
            }
        }
        
        internal static string vui_long_chon_dia_chi_lien_lac {
            get {
                return ResourceManager.GetString("vui_long_chon_dia_chi_lien_lac", resourceCulture);
            }
        }
        
        internal static string vui_long_chon_dia_chi_thuong_tru {
            get {
                return ResourceManager.GetString("vui_long_chon_dia_chi_thuong_tru", resourceCulture);
            }
        }
        
        internal static string vui_long_chon_gioi_tinh {
            get {
                return ResourceManager.GetString("vui_long_chon_gioi_tinh", resourceCulture);
            }
        }
        
        internal static string vui_long_chon_loai_khach_hang {
            get {
                return ResourceManager.GetString("vui_long_chon_loai_khach_hang", resourceCulture);
            }
        }
        
        internal static string vui_long_chon_ngay_sinh {
            get {
                return ResourceManager.GetString("vui_long_chon_ngay_sinh", resourceCulture);
            }
        }
        
        internal static string vui_long_chon_nguoi_dai_dien {
            get {
                return ResourceManager.GetString("vui_long_chon_nguoi_dai_dien", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_ho_ten {
            get {
                return ResourceManager.GetString("vui_long_nhap_ho_ten", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_mat_khau_cu {
            get {
                return ResourceManager.GetString("vui_long_nhap_mat_khau_cu", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_mat_khau_moi {
            get {
                return ResourceManager.GetString("vui_long_nhap_mat_khau_moi", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_password_nhieu_hon_6_ky_tu {
            get {
                return ResourceManager.GetString("vui_long_nhap_password_nhieu_hon_6_ky_tu", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_sdt {
            get {
                return ResourceManager.GetString("vui_long_nhap_sdt", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_sdt_cong_ty {
            get {
                return ResourceManager.GetString("vui_long_nhap_sdt_cong_ty", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_so_cmnd {
            get {
                return ResourceManager.GetString("vui_long_nhap_so_cmnd", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_so_giay_phep_kinh_doanh {
            get {
                return ResourceManager.GetString("vui_long_nhap_so_giay_phep_kinh_doanh", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_so_nha_duong_phuong {
            get {
                return ResourceManager.GetString("vui_long_nhap_so_nha_duong_phuong", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_ten_cong_ty {
            get {
                return ResourceManager.GetString("vui_long_nhap_ten_cong_ty", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_tieu_de {
            get {
                return ResourceManager.GetString("vui_long_nhap_tieu_de", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_xac_nhan_mat_khau_moi {
            get {
                return ResourceManager.GetString("vui_long_nhap_xac_nhan_mat_khau_moi", resourceCulture);
            }
        }
        
        internal static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        internal static string xac_nhan {
            get {
                return ResourceManager.GetString("xac_nhan", resourceCulture);
            }
        }
        
        internal static string xac_nhan_mat_khau_khong_dung {
            get {
                return ResourceManager.GetString("xac_nhan_mat_khau_khong_dung", resourceCulture);
            }
        }
        
        internal static string xem_anh_mat_sau_cmnd {
            get {
                return ResourceManager.GetString("xem_anh_mat_sau_cmnd", resourceCulture);
            }
        }
        
        internal static string xem_anh_mat_truoc_cmnd {
            get {
                return ResourceManager.GetString("xem_anh_mat_truoc_cmnd", resourceCulture);
            }
        }
        
        internal static string xem_them {
            get {
                return ResourceManager.GetString("xem_them", resourceCulture);
            }
        }
        
        internal static string xoa_nguoi_uy_quyen_that_bai {
            get {
                return ResourceManager.GetString("xoa_nguoi_uy_quyen_that_bai", resourceCulture);
            }
        }
    }
}
